Repository rilling/OpenTracks-Concordia, pull requests merged in 2023-04, with the labels that each got.

#416 Group #19. Adding relevant text fields in User's profile settings page.
  src/main/res/layout/user_profile_setting.xml
Labels: enhancement, G#19

#405 Features/group 3/soham
  src/main/java/de/dennisguse/opentracks/ui/aggregatedStatistics/AggregatedStatisticsAdapter.java
  src/main/res/layout/statistics_recorded.xml
Labels: G#3

#423 Code fix for recent merge
  src/main/java/de/dennisguse/opentracks/io/file/importer/ImportViewModel.java
  src/main/java/de/dennisguse/opentracks/util/ExportUtils.java
  src/main/java/de/dennisguse/opentracks/util/IntentUtils.java
Labels: G#16, fix

#506 #503. Finish technical debt of misleading column usage.
  src/main/java/de/dennisguse/opentracks/TrackListActivity.java
Labels: Technical Debt, G#1

#505 Issue#245 Add a simple moving average to the charts "By time" and "By Distance"
  src/androidTest/java/de/dennisguse/opentracks/stats/TrackStatisticsTest.java
  src/main/java/de/dennisguse/opentracks/stats/TrackStatistics.java
Labels: G#7

#482 resolved sonarqube related issue-436
  .idea/sonarlint/issuestore/index.pb
  src/main/java/de/dennisguse/opentracks/chart/ChartView.java
Labels: Technical Debt, G#8

#523 Feature g9 calories feature quality
  src/main/java/de/dennisguse/opentracks/data/models/Altitude.java
  src/main/java/de/dennisguse/opentracks/data/models/Distance.java
  src/main/java/de/dennisguse/opentracks/data/models/Speed.java
  src/main/java/de/dennisguse/opentracks/data/models/TrackPoint.java
  src/main/java/de/dennisguse/opentracks/sensors/AltitudeSumManager.java
  src/main/java/de/dennisguse/opentracks/ui/intervals/IntervalStatistics.java
Labels: G#9, Deliverable 3

#304 Adding a visualization of the last Track on the Stats tab
  build.gradle
  gradle.properties
  src/debug/AndroidManifest.xml
  src/debug/res/layout/statistics_recorded_enhancement.xml
  src/main/AndroidManifest.xml
  src/main/java/de/dennisguse/opentracks/TrackRecordedActivity.java
  src/main/java/de/dennisguse/opentracks/TrackRecordingActivity.java
  src/main/java/de/dennisguse/opentracks/ViewTrackMap.java
  src/main/java/de/dennisguse/opentracks/data/TrackDataHub.java
  src/main/java/de/dennisguse/opentracks/data/models/LocationPoints.java
  src/main/java/de/dennisguse/opentracks/ui/aggregatedStatistics/AggregatedStatisticsActivity.java
  src/main/java/de/dennisguse/opentracks/ui/aggregatedStatistics/ConfirmDeleteDialogFragment.java
  src/main/java/de/dennisguse/opentracks/ui/aggregatedStatistics/FilterDialogFragment.java
  src/main/java/de/dennisguse/opentracks/ui/util/DialogUtils.java
  src/main/res/layout/statistics_recorded.xml
  src/main/res/layout/track_recorded.xml
  src/main/res/values/strings.xml
Labels: G#3, Deliverable 3
