Repository rilling/OpenTracks-Concordia, pull requests merged in 2023-02, with the labels that each got.

#55 Fixes #29: Rename local variable 'speed_kmh' to 'speedKMH'
  src/main/java/de/dennisguse/opentracks/data/models/Speed.java
Labels: Technical Debt, G#18

#64 [Technical Debt] #61 Removed depricated code and updated to newest class
  src/main/java/de/dennisguse/opentracks/publicapi/StartRecording.java
Labels: Technical Debt, G#18

#72 Fixed constant naming convention - Issue 33
  src/main/java/de/dennisguse/opentracks/io/file/TrackFileFormat.java
Labels: G#16

#141 G9 hm 40206570 open tracks
  src/androidTest/java/de/dennisguse/opentracks/data/models/SpeedFormatterTest.java
  src/main/java/de/dennisguse/opentracks/TrackStoppedActivity.java
  src/main/java/de/dennisguse/opentracks/data/models/SpeedFormatter.java
  src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordedFragment.java
  src/main/java/de/dennisguse/opentracks/services/TrackRecordingServiceNotificationManager.java
  src/main/java/de/dennisguse/opentracks/share/DescriptionGenerator.java
  src/main/java/de/dennisguse/opentracks/ui/aggregatedStatistics/AggregatedStatisticsAdapter.java
  src/main/java/de/dennisguse/opentracks/ui/intervals/IntervalStatisticsAdapter.java
  src/main/java/de/dennisguse/opentracks/viewmodels/GenericStatisticsViewHolder.java
Labels: Technical Debt, G#9, Technical Debt Deliverable 1

#186 Update BluetoothRemoteSensorManager
  src/main/java/de/dennisguse/opentracks/sensors/BluetoothRemoteSensorManager.java
Labels: G#6

#224 removed the usage of deprecated method and added a nullability check
  build.gradle
  gradle.properties
  src/main/java/de/dennisguse/opentracks/ui/aggregatedStatistics/ConfirmDeleteDialogFragment.java
  src/main/java/de/dennisguse/opentracks/ui/util/DialogUtils.java
Labels: bug, Technical Debt, G#3

#229 Solved issue#225
  src/main/java/de/dennisguse/opentracks/viewmodels/ClockViewHolder.java
Labels: Technical Debt, G#19, Technical Debt Deliverable 1
